[package]
name = "spf"
version = "0.5.2"
description = "Simple package format"
edition = "2024"
authors = ["Owen DeBiasio <owen.debiasio@gmail.com>"]
license = "GPL-3.0-or-later"

[dependencies]
cmd-exists = "0.1.2"
glob = "0.3.4"
self-replace = "1.5.0"

[profile.release]
lto = true
codegen-units = 1

[package.metadata.deb]
maintainer = "Owen DeBiasio <owen.debiasio@gmail.com>"
copyright = "2026, Owen DeBiasio"
license-file = ["LICENSE", "4"]
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/spf", "usr/bin/spf", "755"],
    ["LICENSE", "usr/share/doc/spf/copyright", "644"],
    ["changes.md", "usr/share/doc/spf/changes.md", "644"],
    ["README.md", "usr/share/doc/spf/README.md", "644"],
]

[package.metadata.generate-rpm]
auto-req = "auto"
group = "Applications/Utilities"
release = "1"
assets = [
    { source = "target/release/spf", dest = "/usr/bin/spf", mode = "755" },
    { source = "LICENSE", dest = "/usr/share/doc/spf/copyright", mode = "644" },
    { source = "changes.md", dest = "/usr/share/doc/spf/changes.md", mode = "644" },
    { source = "README.md", dest = "/usr/share/doc/spf/README.md", mode = "644" },
]
