words = [
    "Clippy",
    "Debiasio",
    "Linters",
    "Rustup",
    "Swatinem",
    "arga",
    "argb",
    "chmod",
    "cli",
    "dtolnay",
    "gplv",
    "markdownlint",
    "necho",
    "nexit",
    "ninstalled",
    "prettierrc",
    "rustfmt",
    "shellcheck",
    "shfmt",
    "smh",
    "softprops",
]
