[toolchain]
channel = "stable"
components = [ "rustfmt", "clippy", "rust-analyzer", "rust-src" ]
targets = [
    "aarch64-unknown-linux-gnu", # arm64 build
    "x86_64-unknown-linux-gnu" # x64 build
]
