name: Release and Deploy

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      pkg_version: ${{ steps.cargo_info.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Install Debian & RPM Packaging Utilities
        run: cargo install cargo-generate-rpm cargo-deb

      - name: Get Cargo version
        id: cargo_info
        run: |
          VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.manifest_path == "'"$PWD"/Cargo.toml'") | .version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get changelog
        id: changelog_reader
        run: |
          TAG="${{ github.ref_name }}"
          awk -v tag="$TAG" '
            $0 ~ "^## " tag {p=1; next} 
            p && /^## / {p=0} 
            p {print}
          ' changes.md > latest_changelog.txt
          echo "Changelog extracted for $TAG:"
          cat latest_changelog.txt

      - name: Run Main Packaging Script
        run: |
          echo -e "#!/bin/bash\necho '> Skipping format in CI'\nexit 0" > ./dev/format.sh
          chmod +x ./dev/format.bash

          chmod +x ./dev/package.bash

          ./dev/package.bash "${{ github.ref_name }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: packages/spf-*
          body_path: latest_changelog.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
